server:
  port: 8771

spring:
  ai:
    openai:
      base-url: http://127.0.0.1:8771
      api-key: sk-hpWgs2M83327R5qc9b517f07781b4dE483F260Fb20DaCe18
      chat:
        options:
          model: gpt-4.1-mini
      embedding-model: text-embedding-ada-002
      embedding:
        options:
          num-batch: 1536
    # 个人配置，通过 http://127.0.0.1:8090 代理出去
    agent:
      base-url: https://apis.itedus.cn
      api-key: sk-2GQTYTNoQSs7qizlE9F00bD84d254c2994D44d6410B0Ac8f

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml